### PR TITLE
Don't use appraisal in CI

### PR DESCRIPTION
**Pull request by krororo**
Use the `BUNDLE_GEMFILE` environment variable to simplify running `bundle install`.

### CODE REVIEW

**Review by QWYNG — APPROVED** [review]
lgtm
@krororo Are you going to delete files related to appraisal?

**Comment by krororo** [comment]
@QWYNG 

> Are you going to delete files related to appraisal?

No, I think appraisal will continue to be useful to manage multiple gemfiles.

**Review by mkmn — APPROVED** [review]
👍

**Comment by krororo** [comment]
Thanks!

**Pull request merged**
