### PR TITLE
Do not run CI against rails_main

### PR DESCRIPTION
**Pull request by wata727**
Currently, we run CI against the `rails_main` on every PR, but unfortunately we don't have time to fix the failed tests right away.

This PR proposes removing the CI for the `rails_main`, since unfixed falling tests are confusing.

### CODE REVIEW

**Comment by krororo** [comment]
I would like to see this removed as well.
https://github.com/kufu/activerecord-bitemporal/blob/31e2d799225580110c6681ad8fe4764e78547184/Appraisals#L3-L5

**Comment by wata727** [comment]
Fixed https://github.com/kufu/activerecord-bitemporal/compare/0807682c04ad2c52994e06c46fac87dc1f505b32..2381eec0736d7a7ca422828b75d25e52f70b87f9

**Review by krororo — APPROVED** [review]
🧹

**Review by kumaie-shr — COMMENTED** [review]
LGTM 🚀

**Review by kumaie-shr — APPROVED** [review]

**Pull request merged**
