### PR TITLE
Add some files to .gitignore

### PR DESCRIPTION
**Pull request by krororo**
This PR is adds some files to `.gitignore`.

* `.rspec_status`
  * This file is defined in [spec_helper](https://github.com/kufu/activerecord-bitemporal/blob/ed610e458c58cc494287c810823ff276f6f93e50/spec/spec_helper.rb#L14)
* `Gemfile.lock`
  * Follow up #126

### CODE REVIEW

**Review by mkmn — APPROVED** [review]
👍

**Review by osyo-manga — APPROVED** [review]
Thanks!

**Review by osyo-manga — APPROVED** [review]
Thanks!

**Comment by krororo** [comment]
Thanks for the review!

**Pull request merged**
